clear;
L_tri=7.5;
%O1=(0,5,25);O2=(0,5,20);O3=(5*cos(pi/6),5*sin(pi/6),20);O4=(5*cos(pi/6),5*sin(pi/6),25)
xo=5*cos(pi/6);
yo=5*sin(pi/6);
zo=27;
x_target=0;
y_target=5;
z_target=27;
x_ball1=5;
y_ball1=10;
z_ball1=27;
x_ball2=-7;
y_ball2=-7;
z_ball2=27;
x_ball3=3;
y_ball3=6;
z_ball3=27;
x_ball4=6;
y_ball4=-4;
z_ball4=27;
xa=xo+L_tri/2;
ya=yo-L_tri/(2*3^0.5);
za=zo;
xb=xo-L_tri/2;
yb=yo-L_tri/(2*3^0.5);
zb=zo;
xc=xo;
yc=yo+L_tri/(3^0.5);
zc=zo;
xg=10*cos(pi/6);
yg=-10*sin(pi/6);
zg=0;
xh=-xg;
yh=yg;
zh=zg;
xi=0;
yi=10;
zi=0;

L1=20.8;
L2=10.8;
syms xd yd zd xe ye ze xf yf zf;
eq1=(xd-xa)^2+(yd-ya)^2+(za-zd)^2==L1^2;
eq2=(xd-xg)^2+(yd-yg)^2+(zd-zg)^2==L2^2;
eq3=xd==xg;

eq4=(xb-xe)^2+(yb-ye)^2+(zb-ze)^2==L1^2;
eq5=(xh-xe)^2+(yh-ye)^2+(zh-ze)^2==L2^2;
eq6=xe-xh==(yh-ye)*3^0.5;

eq7=(xc-xf)^2+(yc-yf)^2+(zc-zf)^2==L1^2;
eq8=(xi-xf)^2+(yi-yf)^2+(zi-zf)^2==L2^2;
eq9=xi-xf==(yi-yf)*3^0.5;

eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
sol=solve(eqns,[xd,yd,zd,xe,ye,ze,xf,yf,zf]);
xd=double(sol.xd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
yd=double(sol.yd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
zd=double(sol.zd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
xe=double(sol.xe(sol.yd>0 & sol.xe>-5 & sol.xf<0));
ye=double(sol.ye(sol.yd>0 & sol.xe>-5 & sol.xf<0));
ze=double(sol.ze(sol.yd>0 & sol.xe>-5 & sol.xf<0));
xf=double(sol.xf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
yf=double(sol.yf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
zf=double(sol.zf(sol.yd>0 & sol.xe>-5 & sol.xf<0));

L3=4.4;
L4=4.2;
L5=5.3;
xj=xg;
yj=yg+L3*(zd-zg)/L2;
zj=zg-L3*(yd-yg)/L2;

syms xk yk zk;
eq1=(xk-xh)^2+(yk-yh)^2+(zk-zh)^2==L3^2;
eq2=(xk-xe)^2+(yk-ye)^2+(zk-ze)^2==L3^2+L2^2;
eq3=-sin(pi/6)*(xk-xh)-cos(pi/6)*(yk-yh)==0;
eqns=[eq1,eq2,eq3];
sol=solve(eqns,[xk,yk,zk]);
xk=double(sol.xk(sol.xk>xh));
yk=double(sol.yk(sol.xk>xh));
zk=double(sol.zk(sol.xk>xh));

syms xl yl zl;
eq1=(xl-xi)^2+(yl-yi)^2+(zl-zi)^2==L3^2;
eq2=(xl-xf)^2+(yl-yf)^2+(zl-zf)^2==L2^2+L3^2;
eq3=-sin(pi/6)*(xl-xi)+cos(pi/6)*(yl-yi)==0;
eqns=[eq1,eq2,eq3];
sol=solve(eqns,[xl,yl,zl]);
xl=double(sol.xl(sol.xl<0));
yl=double(sol.yl(sol.xl<0));
zl=double(sol.zl(sol.xl<0));

xs=6*sin(pi/6);
ys=-6*cos(pi/6);
zs=-1;
xu=-6;
yu=0;
zu=-1;
xv=xs;
yv=-ys;
zv=-1;

syms xm ym zm xp yp zp xq yq zq;
eq1=(xm-xj)^2+(ym-yj)^2+(zm-zj)^2==L4^2;
eq2=(xm-xs)^2+(ym-ys)^2+(zm-zs)^2==L5^2;
eq3=zs==zm;
eq4=(xp-xk)^2+(yp-yk)^2+(zp-zk)^2==L4^2;
eq5=(xp-xu)^2+(yp-yu)^2+(zp-zu)^2==L5^2;
eq6=zp==zu;
eq7=(xq-xl)^2+(yq-yl)^2+(zq-zl)^2==L4^2;
eq8=(xq-xv)^2+(yq-yv)^2+(zq-zv)^2==L5^2;
eq9=zq==zv;
eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
sol=solve(eqns,[xm,ym,zm,xp,yp,zp,xq,yq,zq]);
xm=double(sol.xm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
ym=double(sol.ym(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
zm=double(sol.zm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
xp=double(sol.xp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
yp=double(sol.yp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
zp=double(sol.zp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
xq=double(sol.xq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
yq=double(sol.yq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
zq=double(sol.zq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));


alpha=pi*3/4;
L6=2.5;
xs1=xs+L6*cos(alpha+atan2(ym-ys,xm-xs));
ys1=ys+L6*sin(alpha+atan2(ym-ys,xm-xs));
zs1=zm;
xu1=xu+L6*cos(alpha+atan2(yp-yu,xp-xu));
yu1=yu+L6*sin(alpha+atan2(yp-yu,xp-xu));
zu1=zp;
xv1=xv+L6*cos(alpha+atan2(yq-yv,xq-xv));
yv1=yv+L6*sin(alpha+atan2(yq-yv,xq-xv));
zv1=zq;

rho_s=(xs1^2+ys1^2+zs1^2)^0.5;
rho_u=(xu1^2+yu1^2+zu1^2)^0.5;
rho_v=(xv1^2+yv1^2+zv1^2)^0.5;

positions.xo=xo;
positions.yo=yo;
positions.zo=zo;
positions.xa=xa;
positions.ya=ya;
positions.za=za;
positions.xb=xb;
positions.yb=yb;
positions.zb=zb;
positions.xc=xc;
positions.yc=yc;
positions.zc=zc;
positions.xd=xd;
positions.yd=yd;
positions.zd=zd;
positions.xe=xe;
positions.ye=ye;
positions.ze=ze;
positions.xf=xf;
positions.yf=yf;
positions.zf=zf;
positions.xg=xg;
positions.yg=yg;
positions.zg=zg;
positions.xh=xh;
positions.yh=yh;
positions.zh=zh;
positions.xi=xi;
positions.yi=yi;
positions.zi=zi;
positions.xj=xj;
positions.yj=yj;
positions.zj=zj;
positions.xk=xk;
positions.yk=yk;
positions.zk=zk;
positions.xl=xl;
positions.yl=yl;
positions.zl=zl;
positions.xm=xm;
positions.ym=ym;
positions.zm=zm;
positions.xp=xp;
positions.yp=yp;
positions.zp=zp;
positions.xq=xq;
positions.yq=yq;
positions.zq=zq;
positions.xs=xs;
positions.ys=ys;
positions.zs=zs;
positions.xu=xu;
positions.yu=yu;
positions.zu=zu;
positions.xv=xv;
positions.yv=yv;
positions.zv=zv;
positions.xs1=xs1;
positions.ys1=ys1;
positions.zs1=zs1;
positions.xu1=xu1;
positions.yu1=yu1;
positions.zu1=zu1;
positions.xv1=xv1;
positions.yv1=yv1;
positions.zv1=zv1;
positions.rho_s=rho_s;
positions.rho_u=rho_u;
positions.rho_v=rho_v;
positions.x_target=x_target;
positions.y_target=y_target;
positions.z_target=z_target;

for i=-10:0.5:0
    positions.xo=xo+i;
    positions.yo=yo-10;
    positions.zo=zo;
    positions.xa=xa+i;
    positions.ya=ya-10;
    positions.za=za;
    positions.xb=xb+i;
    positions.yb=yb-10;
    positions.zb=zb;
    positions.xc=xc+i;
    positions.yc=yc-10;
    positions.zc=zc;
    positions.xd=xd+i;
    positions.yd=yd-10;
    positions.zd=zd;
    positions.xe=xe+i;
    positions.ye=ye-10;
    positions.ze=ze;
    positions.xf=xf+i;
    positions.yf=yf-10;
    positions.zf=zf;
    positions.xg=xg+i;
    positions.yg=yg-10;
    positions.zg=zg;
    positions.xh=xh+i;
    positions.yh=yh-10;
    positions.zh=zh;
    positions.xi=xi+i;
    positions.yi=yi-10;
    positions.zi=zi;
    positions.xj=xj+i;
    positions.yj=yj-10;
    positions.zj=zj;
    positions.xk=xk+i;
    positions.yk=yk-10;
    positions.zk=zk;
    positions.xl=xl+i;
    positions.yl=yl-10;
    positions.zl=zl;
    positions.xm=xm+i;
    positions.ym=ym-10;
    positions.zm=zm;
    positions.xp=xp+i;
    positions.yp=yp-10;
    positions.zp=zp;
    positions.xq=xq+i;
    positions.yq=yq-10;
    positions.zq=zq;
    positions.xs=xs+i;
    positions.ys=ys-10;
    positions.zs=zs;
    positions.xu=xu+i;
    positions.yu=yu-10;
    positions.zu=zu;
    positions.xv=xv+i;
    positions.yv=yv-10;
    positions.zv=zv;
    positions.xs1=xs1+i;
    positions.ys1=ys1-10;
    positions.zs1=zs1;
    positions.xu1=xu1+i;
    positions.yu1=yu1-10;
    positions.zu1=zu1;
    positions.xv1=xv1+i;
    positions.yv1=yv1-10;
    positions.zv1=zv1;
    positions.rho_s=rho_s;
    positions.rho_u=rho_u;
    positions.rho_v=rho_v;
    positions.x_target=x_target;
    positions.y_target=y_target;
    positions.z_target=z_target;
    fileID=fopen('claw_machine.txt','a');
    dispcontent=positions;
    fprintf(fileID,'[%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f]\n',positions.xo,positions.yo,positions.zo,positions.xa,positions.ya,positions.za,positions.xb,positions.yb,positions.zb,positions.xc,positions.yc,positions.zc,positions.xd,positions.yd,positions.zd,positions.xe,positions.ye,positions.ze,positions.xf,positions.yf,positions.zf,positions.xg,positions.yg,positions.zg,positions.xh,positions.yh,positions.zh,positions.xi,positions.yi,positions.zi,positions.xj,positions.yj,positions.zj,positions.xk,positions.yk,positions.zk,positions.xl,positions.yl,positions.zl,positions.xm,positions.ym,positions.zm,positions.xp,positions.yp,positions.zp,positions.xq,positions.yq,positions.zq,positions.xs,positions.ys,positions.zs,positions.xu,positions.yu,positions.zu,positions.xv,positions.yv,positions.zv,positions.xs1,positions.ys1,positions.zs1,positions.xu1,positions.yu1,positions.zu1,positions.xv1,positions.yv1,positions.zv1,positions.x_target,positions.y_target,positions.z_target,x_ball1,y_ball1,z_ball1,x_ball2,y_ball2,z_ball2,x_ball3,y_ball3,z_ball3,x_ball4,y_ball4,z_ball4);

end

for i=-10:0.5:0
    positions.xo=xo;
    positions.yo=yo+i;
    positions.zo=zo;
    positions.xa=xa;
    positions.ya=ya+i;
    positions.za=za;
    positions.xb=xb;
    positions.yb=yb+i;
    positions.zb=zb;
    positions.xc=xc;
    positions.yc=yc+i;
    positions.zc=zc;
    positions.xd=xd;
    positions.yd=yd+i;
    positions.zd=zd;
    positions.xe=xe;
    positions.ye=ye+i;
    positions.ze=ze;
    positions.xf=xf;
    positions.yf=yf+i;
    positions.zf=zf;
    positions.xg=xg;
    positions.yg=yg+i;
    positions.zg=zg;
    positions.xh=xh;
    positions.yh=yh+i;
    positions.zh=zh;
    positions.xi=xi;
    positions.yi=yi+i;
    positions.zi=zi;
    positions.xj=xj;
    positions.yj=yj+i;
    positions.zj=zj;
    positions.xk=xk;
    positions.yk=yk+i;
    positions.zk=zk;
    positions.xl=xl;
    positions.yl=yl+i;
    positions.zl=zl;
    positions.xm=xm;
    positions.ym=ym+i;
    positions.zm=zm;
    positions.xp=xp;
    positions.yp=yp+i;
    positions.zp=zp;
    positions.xq=xq;
    positions.yq=yq+i;
    positions.zq=zq;
    positions.xs=xs;
    positions.ys=ys+i;
    positions.zs=zs;
    positions.xu=xu;
    positions.yu=yu+i;
    positions.zu=zu;
    positions.xv=xv;
    positions.yv=yv+i;
    positions.zv=zv;
    positions.xs1=xs1;
    positions.ys1=ys1+i;
    positions.zs1=zs1;
    positions.xu1=xu1;
    positions.yu1=yu1+i;
    positions.zu1=zu1;
    positions.xv1=xv1;
    positions.yv1=yv1+i;
    positions.zv1=zv1;
    positions.rho_s=rho_s;
    positions.rho_u=rho_u;
    positions.rho_v=rho_v;    
    positions.x_target=x_target;
    positions.y_target=y_target;
    positions.z_target=z_target;
    fileID=fopen('claw_machine.txt','a');
    dispcontent=positions;
    fprintf(fileID,'[%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f]\n',positions.xo,positions.yo,positions.zo,positions.xa,positions.ya,positions.za,positions.xb,positions.yb,positions.zb,positions.xc,positions.yc,positions.zc,positions.xd,positions.yd,positions.zd,positions.xe,positions.ye,positions.ze,positions.xf,positions.yf,positions.zf,positions.xg,positions.yg,positions.zg,positions.xh,positions.yh,positions.zh,positions.xi,positions.yi,positions.zi,positions.xj,positions.yj,positions.zj,positions.xk,positions.yk,positions.zk,positions.xl,positions.yl,positions.zl,positions.xm,positions.ym,positions.zm,positions.xp,positions.yp,positions.zp,positions.xq,positions.yq,positions.zq,positions.xs,positions.ys,positions.zs,positions.xu,positions.yu,positions.zu,positions.xv,positions.yv,positions.zv,positions.xs1,positions.ys1,positions.zs1,positions.xu1,positions.yu1,positions.zu1,positions.xv1,positions.yv1,positions.zv1,positions.x_target,positions.y_target,positions.z_target,x_ball1,y_ball1,z_ball1,x_ball2,y_ball2,z_ball2,x_ball3,y_ball3,z_ball3,x_ball4,y_ball4,z_ball4);

end

for i=27:-0.5:21
    
    xo=5*cos(pi/6);
    yo=5*sin(pi/6);
    zo=i;
    xa=xo+L_tri/2;
    ya=yo-L_tri/(2*3^0.5);
    za=zo;
    xb=xo-L_tri/2;
    yb=yo-L_tri/(2*3^0.5);
    zb=zo;
    xc=xo;
    yc=yo+L_tri/(3^0.5);
    zc=zo;
    xg=10*cos(pi/6);
    yg=-10*sin(pi/6);
    zg=0;
    xh=-xg;
    yh=yg;
    zh=zg;
    xi=0;
    yi=10;
    zi=0;

    L1=20.8;
    L2=10.8;
    syms xd yd zd xe ye ze xf yf zf;
    eq1=(xd-xa)^2+(yd-ya)^2+(za-zd)^2==L1^2;
    eq2=(xd-xg)^2+(yd-yg)^2+(zd-zg)^2==L2^2;
    eq3=xd==xg;

    eq4=(xb-xe)^2+(yb-ye)^2+(zb-ze)^2==L1^2;
    eq5=(xh-xe)^2+(yh-ye)^2+(zh-ze)^2==L2^2;
    eq6=xe-xh==(yh-ye)*3^0.5;

    eq7=(xc-xf)^2+(yc-yf)^2+(zc-zf)^2==L1^2;
    eq8=(xi-xf)^2+(yi-yf)^2+(zi-zf)^2==L2^2;
    eq9=xi-xf==(yi-yf)*3^0.5;

    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xd,yd,zd,xe,ye,ze,xf,yf,zf]);
    xd=double(sol.xd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yd=double(sol.yd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zd=double(sol.zd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xe=double(sol.xe(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ye=double(sol.ye(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ze=double(sol.ze(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xf=double(sol.xf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yf=double(sol.yf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zf=double(sol.zf(sol.yd>0 & sol.xe>-5 & sol.xf<0));

    L3=4.4;
    L4=4.2;
    L5=5.3;
    xj=xg;
    yj=yg+L3*(zd-zg)/L2;
    zj=zg-L3*(yd-yg)/L2;

    syms xk yk zk;
    eq1=(xk-xh)^2+(yk-yh)^2+(zk-zh)^2==L3^2;
    eq2=(xk-xe)^2+(yk-ye)^2+(zk-ze)^2==L3^2+L2^2;
    eq3=-sin(pi/6)*(xk-xh)-cos(pi/6)*(yk-yh)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xk,yk,zk]);
    xk=double(sol.xk(sol.xk>xh));
    yk=double(sol.yk(sol.xk>xh));
    zk=double(sol.zk(sol.xk>xh));

    syms xl yl zl;
    eq1=(xl-xi)^2+(yl-yi)^2+(zl-zi)^2==L3^2;
    eq2=(xl-xf)^2+(yl-yf)^2+(zl-zf)^2==L2^2+L3^2;
    eq3=-sin(pi/6)*(xl-xi)+cos(pi/6)*(yl-yi)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xl,yl,zl]);
    xl=double(sol.xl(sol.xl<0));
    yl=double(sol.yl(sol.xl<0));
    zl=double(sol.zl(sol.xl<0));

    xs=6*sin(pi/6);
    ys=-6*cos(pi/6);
    zs=-1;
    xu=-6;
    yu=0;
    zu=-1;
    xv=xs;
    yv=-ys;
    zv=-1;

    syms xm ym zm xp yp zp xq yq zq;
    eq1=(xm-xj)^2+(ym-yj)^2+(zm-zj)^2==L4^2;
    eq2=(xm-xs)^2+(ym-ys)^2+(zm-zs)^2==L5^2;
    eq3=zs==zm;
    eq4=(xp-xk)^2+(yp-yk)^2+(zp-zk)^2==L4^2;
    eq5=(xp-xu)^2+(yp-yu)^2+(zp-zu)^2==L5^2;
    eq6=zp==zu;
    eq7=(xq-xl)^2+(yq-yl)^2+(zq-zl)^2==L4^2;
    eq8=(xq-xv)^2+(yq-yv)^2+(zq-zv)^2==L5^2;
    eq9=zq==zv;
    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xm,ym,zm,xp,yp,zp,xq,yq,zq]);
    xm=double(sol.xm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    ym=double(sol.ym(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zm=double(sol.zm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xp=double(sol.xp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yp=double(sol.yp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zp=double(sol.zp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xq=double(sol.xq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yq=double(sol.yq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zq=double(sol.zq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));


    alpha=pi*3/4;
    L6=2.5;
    xs1=xs+L6*cos(alpha+atan2(ym-ys,xm-xs));
    ys1=ys+L6*sin(alpha+atan2(ym-ys,xm-xs));
    zs1=zm;
    xu1=xu+L6*cos(alpha+atan2(yp-yu,xp-xu));
    yu1=yu+L6*sin(alpha+atan2(yp-yu,xp-xu));
    zu1=zp;
    xv1=xv+L6*cos(alpha+atan2(yq-yv,xq-xv));
    yv1=yv+L6*sin(alpha+atan2(yq-yv,xq-xv));
    zv1=zq;

    rho_s=(xs1^2+ys1^2+zs1^2)^0.5;
    rho_u=(xu1^2+yu1^2+zu1^2)^0.5;
    rho_v=(xv1^2+yv1^2+zv1^2)^0.5;

    positions.xo=xo;
    positions.yo=yo;
    positions.zo=zo;
    positions.xa=xa;
    positions.ya=ya;
    positions.za=za;
    positions.xb=xb;
    positions.yb=yb;
    positions.zb=zb;
    positions.xc=xc;
    positions.yc=yc;
    positions.zc=zc;
    positions.xd=xd;
    positions.yd=yd;
    positions.zd=zd;
    positions.xe=xe;
    positions.ye=ye;
    positions.ze=ze;
    positions.xf=xf;
    positions.yf=yf;
    positions.zf=zf;
    positions.xg=xg;
    positions.yg=yg;
    positions.zg=zg;
    positions.xh=xh;
    positions.yh=yh;
    positions.zh=zh;
    positions.xi=xi;
    positions.yi=yi;
    positions.zi=zi;
    positions.xj=xj;
    positions.yj=yj;
    positions.zj=zj;
    positions.xk=xk;
    positions.yk=yk;
    positions.zk=zk;
    positions.xl=xl;
    positions.yl=yl;
    positions.zl=zl;
    positions.xm=xm;
    positions.ym=ym;
    positions.zm=zm;
    positions.xp=xp;
    positions.yp=yp;
    positions.zp=zp;
    positions.xq=xq;
    positions.yq=yq;
    positions.zq=zq;
    positions.xs=xs;
    positions.ys=ys;
    positions.zs=zs;
    positions.xu=xu;
    positions.yu=yu;
    positions.zu=zu;
    positions.xv=xv;
    positions.yv=yv;
    positions.zv=zv;
    positions.xs1=xs1;
    positions.ys1=ys1;
    positions.zs1=zs1;
    positions.xu1=xu1;
    positions.yu1=yu1;
    positions.zu1=zu1;
    positions.xv1=xv1;
    positions.yv1=yv1;
    positions.zv1=zv1;
    positions.x_target=x_target;
    positions.y_target=y_target;
    positions.z_target=z_target;
    disp(positions);
    fileID=fopen('claw_machine.txt','a');
    dispcontent=positions;
    fprintf(fileID,'[%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f]\n',positions.xo,positions.yo,positions.zo,positions.xa,positions.ya,positions.za,positions.xb,positions.yb,positions.zb,positions.xc,positions.yc,positions.zc,positions.xd,positions.yd,positions.zd,positions.xe,positions.ye,positions.ze,positions.xf,positions.yf,positions.zf,positions.xg,positions.yg,positions.zg,positions.xh,positions.yh,positions.zh,positions.xi,positions.yi,positions.zi,positions.xj,positions.yj,positions.zj,positions.xk,positions.yk,positions.zk,positions.xl,positions.yl,positions.zl,positions.xm,positions.ym,positions.zm,positions.xp,positions.yp,positions.zp,positions.xq,positions.yq,positions.zq,positions.xs,positions.ys,positions.zs,positions.xu,positions.yu,positions.zu,positions.xv,positions.yv,positions.zv,positions.xs1,positions.ys1,positions.zs1,positions.xu1,positions.yu1,positions.zu1,positions.xv1,positions.yv1,positions.zv1,positions.x_target,positions.y_target,positions.z_target,x_ball1,y_ball1,z_ball1,x_ball2,y_ball2,z_ball2,x_ball3,y_ball3,z_ball3,x_ball4,y_ball4,z_ball4);



end;

for i=0:1/12:1
    
    xo=5*cos(pi/6)+i*(-5*cos(pi/6));
    yo=5*sin(pi/6)+i*(-5*sin(pi/6)+5);
    zo=21;

    xa=xo+L_tri/2;
    ya=yo-L_tri/(2*3^0.5);
    za=zo;
    xb=xo-L_tri/2;
    yb=yo-L_tri/(2*3^0.5);
    zb=zo;
    xc=xo;
    yc=yo+L_tri/(3^0.5);
    zc=zo;
    xg=10*cos(pi/6);
    yg=-10*sin(pi/6);
    zg=0;
    xh=-xg;
    yh=yg;
    zh=zg;
    xi=0;
    yi=10;
    zi=0;

    L1=20.8;
    L2=10.8;
    syms xd yd zd xe ye ze xf yf zf;
    eq1=(xd-xa)^2+(yd-ya)^2+(za-zd)^2==L1^2;
    eq2=(xd-xg)^2+(yd-yg)^2+(zd-zg)^2==L2^2;
    eq3=xd==xg;

    eq4=(xb-xe)^2+(yb-ye)^2+(zb-ze)^2==L1^2;
    eq5=(xh-xe)^2+(yh-ye)^2+(zh-ze)^2==L2^2;
    eq6=xe-xh==(yh-ye)*3^0.5;

    eq7=(xc-xf)^2+(yc-yf)^2+(zc-zf)^2==L1^2;
    eq8=(xi-xf)^2+(yi-yf)^2+(zi-zf)^2==L2^2;
    eq9=xi-xf==(yi-yf)*3^0.5;

    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xd,yd,zd,xe,ye,ze,xf,yf,zf]);
    xd=double(sol.xd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yd=double(sol.yd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zd=double(sol.zd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xe=double(sol.xe(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ye=double(sol.ye(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ze=double(sol.ze(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xf=double(sol.xf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yf=double(sol.yf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zf=double(sol.zf(sol.yd>0 & sol.xe>-5 & sol.xf<0));

    L3=4.4;
    L4=4.2;
    L5=5.3;
    xj=xg;
    yj=yg+L3*(zd-zg)/L2;
    zj=zg-L3*(yd-yg)/L2;

    syms xk yk zk;
    eq1=(xk-xh)^2+(yk-yh)^2+(zk-zh)^2==L3^2;
    eq2=(xk-xe)^2+(yk-ye)^2+(zk-ze)^2==L3^2+L2^2;
    eq3=-sin(pi/6)*(xk-xh)-cos(pi/6)*(yk-yh)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xk,yk,zk]);
    xk=double(sol.xk(sol.xk>xh));
    yk=double(sol.yk(sol.xk>xh));
    zk=double(sol.zk(sol.xk>xh));

    syms xl yl zl;
    eq1=(xl-xi)^2+(yl-yi)^2+(zl-zi)^2==L3^2;
    eq2=(xl-xf)^2+(yl-yf)^2+(zl-zf)^2==L2^2+L3^2;
    eq3=-sin(pi/6)*(xl-xi)+cos(pi/6)*(yl-yi)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xl,yl,zl]);
    xl=double(sol.xl(sol.xl<0));
    yl=double(sol.yl(sol.xl<0));
    zl=double(sol.zl(sol.xl<0));

    xs=6*sin(pi/6);
    ys=-6*cos(pi/6);
    zs=-1;
    xu=-6;
    yu=0;
    zu=-1;
    xv=xs;
    yv=-ys;
    zv=-1;

    syms xm ym zm xp yp zp xq yq zq;
    eq1=(xm-xj)^2+(ym-yj)^2+(zm-zj)^2==L4^2;
    eq2=(xm-xs)^2+(ym-ys)^2+(zm-zs)^2==L5^2;
    eq3=zs==zm;
    eq4=(xp-xk)^2+(yp-yk)^2+(zp-zk)^2==L4^2;
    eq5=(xp-xu)^2+(yp-yu)^2+(zp-zu)^2==L5^2;
    eq6=zp==zu;
    eq7=(xq-xl)^2+(yq-yl)^2+(zq-zl)^2==L4^2;
    eq8=(xq-xv)^2+(yq-yv)^2+(zq-zv)^2==L5^2;
    eq9=zq==zv;
    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xm,ym,zm,xp,yp,zp,xq,yq,zq]);
    xm=double(sol.xm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    ym=double(sol.ym(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zm=double(sol.zm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xp=double(sol.xp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yp=double(sol.yp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zp=double(sol.zp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xq=double(sol.xq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yq=double(sol.yq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zq=double(sol.zq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));


    alpha=pi*3/4;
    L6=2.5;
    xs1=xs+L6*cos(alpha+atan2(ym-ys,xm-xs));
    ys1=ys+L6*sin(alpha+atan2(ym-ys,xm-xs));
    zs1=zm;
    xu1=xu+L6*cos(alpha+atan2(yp-yu,xp-xu));
    yu1=yu+L6*sin(alpha+atan2(yp-yu,xp-xu));
    zu1=zp;
    xv1=xv+L6*cos(alpha+atan2(yq-yv,xq-xv));
    yv1=yv+L6*sin(alpha+atan2(yq-yv,xq-xv));
    zv1=zq;

    rho_s=(xs1^2+ys1^2+zs1^2)^0.5;
    rho_u=(xu1^2+yu1^2+zu1^2)^0.5;
    rho_v=(xv1^2+yv1^2+zv1^2)^0.5;

    positions.xo=xo;
    positions.yo=yo;
    positions.zo=zo;
    positions.xa=xa;
    positions.ya=ya;
    positions.za=za;
    positions.xb=xb;
    positions.yb=yb;
    positions.zb=zb;
    positions.xc=xc;
    positions.yc=yc;
    positions.zc=zc;
    positions.xd=xd;
    positions.yd=yd;
    positions.zd=zd;
    positions.xe=xe;
    positions.ye=ye;
    positions.ze=ze;
    positions.xf=xf;
    positions.yf=yf;
    positions.zf=zf;
    positions.xg=xg;
    positions.yg=yg;
    positions.zg=zg;
    positions.xh=xh;
    positions.yh=yh;
    positions.zh=zh;
    positions.xi=xi;
    positions.yi=yi;
    positions.zi=zi;
    positions.xj=xj;
    positions.yj=yj;
    positions.zj=zj;
    positions.xk=xk;
    positions.yk=yk;
    positions.zk=zk;
    positions.xl=xl;
    positions.yl=yl;
    positions.zl=zl;
    positions.xm=xm;
    positions.ym=ym;
    positions.zm=zm;
    positions.xp=xp;
    positions.yp=yp;
    positions.zp=zp;
    positions.xq=xq;
    positions.yq=yq;
    positions.zq=zq;
    positions.xs=xs;
    positions.ys=ys;
    positions.zs=zs;
    positions.xu=xu;
    positions.yu=yu;
    positions.zu=zu;
    positions.xv=xv;
    positions.yv=yv;
    positions.zv=zv;
    positions.xs1=xs1;
    positions.ys1=ys1;
    positions.zs1=zs1;
    positions.xu1=xu1;
    positions.yu1=yu1;
    positions.zu1=zu1;
    positions.xv1=xv1;
    positions.yv1=yv1;
    positions.zv1=zv1;
    positions.x_target=x_target;
    positions.y_target=y_target;
    positions.z_target=z_target;
    disp(positions);
    fileID=fopen('claw_machine.txt','a');
    dispcontent=positions;
    fprintf(fileID,'[%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f]\n',positions.xo,positions.yo,positions.zo,positions.xa,positions.ya,positions.za,positions.xb,positions.yb,positions.zb,positions.xc,positions.yc,positions.zc,positions.xd,positions.yd,positions.zd,positions.xe,positions.ye,positions.ze,positions.xf,positions.yf,positions.zf,positions.xg,positions.yg,positions.zg,positions.xh,positions.yh,positions.zh,positions.xi,positions.yi,positions.zi,positions.xj,positions.yj,positions.zj,positions.xk,positions.yk,positions.zk,positions.xl,positions.yl,positions.zl,positions.xm,positions.ym,positions.zm,positions.xp,positions.yp,positions.zp,positions.xq,positions.yq,positions.zq,positions.xs,positions.ys,positions.zs,positions.xu,positions.yu,positions.zu,positions.xv,positions.yv,positions.zv,positions.xs1,positions.ys1,positions.zs1,positions.xu1,positions.yu1,positions.zu1,positions.xv1,positions.yv1,positions.zv1,positions.x_target,positions.y_target,positions.z_target,x_ball1,y_ball1,z_ball1,x_ball2,y_ball2,z_ball2,x_ball3,y_ball3,z_ball3,x_ball4,y_ball4,z_ball4);



end;

for i=21:0.5:27
    xo=0;
    yo=5;
    zo=i;

    xa=xo+L_tri/2;
    ya=yo-L_tri/(2*3^0.5);
    za=zo;
    xb=xo-L_tri/2;
    yb=yo-L_tri/(2*3^0.5);
    zb=zo;
    xc=xo;
    yc=yo+L_tri/(3^0.5);
    zc=zo;
    xg=10*cos(pi/6);
    yg=-10*sin(pi/6);
    zg=0;
    xh=-xg;
    yh=yg;
    zh=zg;
    xi=0;
    yi=10;
    zi=0;

    L1=20.8;
    L2=10.8;
    syms xd yd zd xe ye ze xf yf zf;
    eq1=(xd-xa)^2+(yd-ya)^2+(za-zd)^2==L1^2;
    eq2=(xd-xg)^2+(yd-yg)^2+(zd-zg)^2==L2^2;
    eq3=xd==xg;

    eq4=(xb-xe)^2+(yb-ye)^2+(zb-ze)^2==L1^2;
    eq5=(xh-xe)^2+(yh-ye)^2+(zh-ze)^2==L2^2;
    eq6=xe-xh==(yh-ye)*3^0.5;

    eq7=(xc-xf)^2+(yc-yf)^2+(zc-zf)^2==L1^2;
    eq8=(xi-xf)^2+(yi-yf)^2+(zi-zf)^2==L2^2;
    eq9=xi-xf==(yi-yf)*3^0.5;

    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xd,yd,zd,xe,ye,ze,xf,yf,zf]);
    xd=double(sol.xd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yd=double(sol.yd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zd=double(sol.zd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xe=double(sol.xe(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ye=double(sol.ye(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ze=double(sol.ze(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xf=double(sol.xf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yf=double(sol.yf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zf=double(sol.zf(sol.yd>0 & sol.xe>-5 & sol.xf<0));

    L3=4.4;
    L4=4.2;
    L5=5.3;
    xj=xg;
    yj=yg+L3*(zd-zg)/L2;
    zj=zg-L3*(yd-yg)/L2;

    syms xk yk zk;
    eq1=(xk-xh)^2+(yk-yh)^2+(zk-zh)^2==L3^2;
    eq2=(xk-xe)^2+(yk-ye)^2+(zk-ze)^2==L3^2+L2^2;
    eq3=-sin(pi/6)*(xk-xh)-cos(pi/6)*(yk-yh)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xk,yk,zk]);
    xk=double(sol.xk(sol.xk>xh));
    yk=double(sol.yk(sol.xk>xh));
    zk=double(sol.zk(sol.xk>xh));

    syms xl yl zl;
    eq1=(xl-xi)^2+(yl-yi)^2+(zl-zi)^2==L3^2;
    eq2=(xl-xf)^2+(yl-yf)^2+(zl-zf)^2==L2^2+L3^2;
    eq3=-sin(pi/6)*(xl-xi)+cos(pi/6)*(yl-yi)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xl,yl,zl]);
    xl=double(sol.xl(sol.xl<0));
    yl=double(sol.yl(sol.xl<0));
    zl=double(sol.zl(sol.xl<0));

    xs=6*sin(pi/6);
    ys=-6*cos(pi/6);
    zs=-1;
    xu=-6;
    yu=0;
    zu=-1;
    xv=xs;
    yv=-ys;
    zv=-1;

    syms xm ym zm xp yp zp xq yq zq;
    eq1=(xm-xj)^2+(ym-yj)^2+(zm-zj)^2==L4^2;
    eq2=(xm-xs)^2+(ym-ys)^2+(zm-zs)^2==L5^2;
    eq3=zs==zm;
    eq4=(xp-xk)^2+(yp-yk)^2+(zp-zk)^2==L4^2;
    eq5=(xp-xu)^2+(yp-yu)^2+(zp-zu)^2==L5^2;
    eq6=zp==zu;
    eq7=(xq-xl)^2+(yq-yl)^2+(zq-zl)^2==L4^2;
    eq8=(xq-xv)^2+(yq-yv)^2+(zq-zv)^2==L5^2;
    eq9=zq==zv;
    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xm,ym,zm,xp,yp,zp,xq,yq,zq]);
    xm=double(sol.xm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    ym=double(sol.ym(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zm=double(sol.zm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xp=double(sol.xp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yp=double(sol.yp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zp=double(sol.zp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xq=double(sol.xq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yq=double(sol.yq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zq=double(sol.zq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));


    alpha=pi*3/4;
    L6=2.5;
    xs1=xs+L6*cos(alpha+atan2(ym-ys,xm-xs));
    ys1=ys+L6*sin(alpha+atan2(ym-ys,xm-xs));
    zs1=zm;
    xu1=xu+L6*cos(alpha+atan2(yp-yu,xp-xu));
    yu1=yu+L6*sin(alpha+atan2(yp-yu,xp-xu));
    zu1=zp;
    xv1=xv+L6*cos(alpha+atan2(yq-yv,xq-xv));
    yv1=yv+L6*sin(alpha+atan2(yq-yv,xq-xv));
    zv1=zq;

    rho_s=(xs1^2+ys1^2+zs1^2)^0.5;
    rho_u=(xu1^2+yu1^2+zu1^2)^0.5;
    rho_v=(xv1^2+yv1^2+zv1^2)^0.5;

    positions.xo=xo;
    positions.yo=yo;
    positions.zo=zo;
    positions.xa=xa;
    positions.ya=ya;
    positions.za=za;
    positions.xb=xb;
    positions.yb=yb;
    positions.zb=zb;
    positions.xc=xc;
    positions.yc=yc;
    positions.zc=zc;
    positions.xd=xd;
    positions.yd=yd;
    positions.zd=zd;
    positions.xe=xe;
    positions.ye=ye;
    positions.ze=ze;
    positions.xf=xf;
    positions.yf=yf;
    positions.zf=zf;
    positions.xg=xg;
    positions.yg=yg;
    positions.zg=zg;
    positions.xh=xh;
    positions.yh=yh;
    positions.zh=zh;
    positions.xi=xi;
    positions.yi=yi;
    positions.zi=zi;
    positions.xj=xj;
    positions.yj=yj;
    positions.zj=zj;
    positions.xk=xk;
    positions.yk=yk;
    positions.zk=zk;
    positions.xl=xl;
    positions.yl=yl;
    positions.zl=zl;
    positions.xm=xm;
    positions.ym=ym;
    positions.zm=zm;
    positions.xp=xp;
    positions.yp=yp;
    positions.zp=zp;
    positions.xq=xq;
    positions.yq=yq;
    positions.zq=zq;
    positions.xs=xs;
    positions.ys=ys;
    positions.zs=zs;
    positions.xu=xu;
    positions.yu=yu;
    positions.zu=zu;
    positions.xv=xv;
    positions.yv=yv;
    positions.zv=zv;
    positions.xs1=xs1;
    positions.ys1=ys1;
    positions.zs1=zs1;
    positions.xu1=xu1;
    positions.yu1=yu1;
    positions.zu1=zu1;
    positions.xv1=xv1;
    positions.yv1=yv1;
    positions.zv1=zv1;
    positions.x_target=x_target;
    positions.y_target=y_target;
    positions.z_target=z_target;
    disp(positions);
    fileID=fopen('claw_machine.txt','a');
    dispcontent=positions;
    fprintf(fileID,'[%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f]\n',positions.xo,positions.yo,positions.zo,positions.xa,positions.ya,positions.za,positions.xb,positions.yb,positions.zb,positions.xc,positions.yc,positions.zc,positions.xd,positions.yd,positions.zd,positions.xe,positions.ye,positions.ze,positions.xf,positions.yf,positions.zf,positions.xg,positions.yg,positions.zg,positions.xh,positions.yh,positions.zh,positions.xi,positions.yi,positions.zi,positions.xj,positions.yj,positions.zj,positions.xk,positions.yk,positions.zk,positions.xl,positions.yl,positions.zl,positions.xm,positions.ym,positions.zm,positions.xp,positions.yp,positions.zp,positions.xq,positions.yq,positions.zq,positions.xs,positions.ys,positions.zs,positions.xu,positions.yu,positions.zu,positions.xv,positions.yv,positions.zv,positions.xs1,positions.ys1,positions.zs1,positions.xu1,positions.yu1,positions.zu1,positions.xv1,positions.yv1,positions.zv1,positions.x_target,positions.y_target,positions.z_target,x_ball1,y_ball1,z_ball1,x_ball2,y_ball2,z_ball2,x_ball3,y_ball3,z_ball3,x_ball4,y_ball4,z_ball4);


end;

for i=0:0.5:3.5
    
    xo=0;
    yo=5;
    zo=27;
    L=L_tri-i;

    xa=xo+L/2;
    ya=yo-L/(2*3^0.5);
    za=zo;
    xb=xo-L/2;
    yb=yo-L/(2*3^0.5);
    zb=zo;
    xc=xo;
    yc=yo+L/(3^0.5);
    zc=zo;
    xg=10*cos(pi/6);
    yg=-10*sin(pi/6);
    zg=0;
    xh=-xg;
    yh=yg;
    zh=zg;
    xi=0;
    yi=10;
    zi=0;

    L1=20.8;
    L2=10.8;
    syms xd yd zd xe ye ze xf yf zf;
    eq1=(xd-xa)^2+(yd-ya)^2+(za-zd)^2==L1^2;
    eq2=(xd-xg)^2+(yd-yg)^2+(zd-zg)^2==L2^2;
    eq3=xd==xg;

    eq4=(xb-xe)^2+(yb-ye)^2+(zb-ze)^2==L1^2;
    eq5=(xh-xe)^2+(yh-ye)^2+(zh-ze)^2==L2^2;
    eq6=xe-xh==(yh-ye)*3^0.5;

    eq7=(xc-xf)^2+(yc-yf)^2+(zc-zf)^2==L1^2;
    eq8=(xi-xf)^2+(yi-yf)^2+(zi-zf)^2==L2^2;
    eq9=xi-xf==(yi-yf)*3^0.5;

    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xd,yd,zd,xe,ye,ze,xf,yf,zf]);
    xd=double(sol.xd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yd=double(sol.yd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zd=double(sol.zd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xe=double(sol.xe(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ye=double(sol.ye(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ze=double(sol.ze(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xf=double(sol.xf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yf=double(sol.yf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zf=double(sol.zf(sol.yd>0 & sol.xe>-5 & sol.xf<0));

    L3=4.4;
    L4=4.2;
    L5=5.3;
    xj=xg;
    yj=yg+L3*(zd-zg)/L2;
    zj=zg-L3*(yd-yg)/L2;

    syms xk yk zk;
    eq1=(xk-xh)^2+(yk-yh)^2+(zk-zh)^2==L3^2;
    eq2=(xk-xe)^2+(yk-ye)^2+(zk-ze)^2==L3^2+L2^2;
    eq3=-sin(pi/6)*(xk-xh)-cos(pi/6)*(yk-yh)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xk,yk,zk]);
    xk=double(sol.xk(sol.xk>xh));
    yk=double(sol.yk(sol.xk>xh));
    zk=double(sol.zk(sol.xk>xh));

    syms xl yl zl;
    eq1=(xl-xi)^2+(yl-yi)^2+(zl-zi)^2==L3^2;
    eq2=(xl-xf)^2+(yl-yf)^2+(zl-zf)^2==L2^2+L3^2;
    eq3=-sin(pi/6)*(xl-xi)+cos(pi/6)*(yl-yi)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xl,yl,zl]);
    xl=double(sol.xl(sol.xl<0));
    yl=double(sol.yl(sol.xl<0));
    zl=double(sol.zl(sol.xl<0));

    xs=6*sin(pi/6);
    ys=-6*cos(pi/6);
    zs=-1;
    xu=-6;
    yu=0;
    zu=-1;
    xv=xs;
    yv=-ys;
    zv=-1;

    syms xm ym zm xp yp zp xq yq zq;
    eq1=(xm-xj)^2+(ym-yj)^2+(zm-zj)^2==L4^2;
    eq2=(xm-xs)^2+(ym-ys)^2+(zm-zs)^2==L5^2;
    eq3=zs==zm;
    eq4=(xp-xk)^2+(yp-yk)^2+(zp-zk)^2==L4^2;
    eq5=(xp-xu)^2+(yp-yu)^2+(zp-zu)^2==L5^2;
    eq6=zp==zu;
    eq7=(xq-xl)^2+(yq-yl)^2+(zq-zl)^2==L4^2;
    eq8=(xq-xv)^2+(yq-yv)^2+(zq-zv)^2==L5^2;
    eq9=zq==zv;
    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xm,ym,zm,xp,yp,zp,xq,yq,zq]);
    xm=double(sol.xm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    ym=double(sol.ym(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zm=double(sol.zm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xp=double(sol.xp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yp=double(sol.yp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zp=double(sol.zp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xq=double(sol.xq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yq=double(sol.yq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zq=double(sol.zq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));


    alpha=pi*3/4;
    L6=2.5;
    xs1=xs+L6*cos(alpha+atan2(ym-ys,xm-xs));
    ys1=ys+L6*sin(alpha+atan2(ym-ys,xm-xs));
    zs1=zm;
    xu1=xu+L6*cos(alpha+atan2(yp-yu,xp-xu));
    yu1=yu+L6*sin(alpha+atan2(yp-yu,xp-xu));
    zu1=zp;
    xv1=xv+L6*cos(alpha+atan2(yq-yv,xq-xv));
    yv1=yv+L6*sin(alpha+atan2(yq-yv,xq-xv));
    zv1=zq;

    rho_s=(xs1^2+ys1^2+zs1^2)^0.5;
    rho_u=(xu1^2+yu1^2+zu1^2)^0.5;
    rho_v=(xv1^2+yv1^2+zv1^2)^0.5;

    positions.xo=xo;
    positions.yo=yo;
    positions.zo=zo;
    positions.xa=xa;
    positions.ya=ya;
    positions.za=za;
    positions.xb=xb;
    positions.yb=yb;
    positions.zb=zb;
    positions.xc=xc;
    positions.yc=yc;
    positions.zc=zc;
    positions.xd=xd;
    positions.yd=yd;
    positions.zd=zd;
    positions.xe=xe;
    positions.ye=ye;
    positions.ze=ze;
    positions.xf=xf;
    positions.yf=yf;
    positions.zf=zf;
    positions.xg=xg;
    positions.yg=yg;
    positions.zg=zg;
    positions.xh=xh;
    positions.yh=yh;
    positions.zh=zh;
    positions.xi=xi;
    positions.yi=yi;
    positions.zi=zi;
    positions.xj=xj;
    positions.yj=yj;
    positions.zj=zj;
    positions.xk=xk;
    positions.yk=yk;
    positions.zk=zk;
    positions.xl=xl;
    positions.yl=yl;
    positions.zl=zl;
    positions.xm=xm;
    positions.ym=ym;
    positions.zm=zm;
    positions.xp=xp;
    positions.yp=yp;
    positions.zp=zp;
    positions.xq=xq;
    positions.yq=yq;
    positions.zq=zq;
    positions.xs=xs;
    positions.ys=ys;
    positions.zs=zs;
    positions.xu=xu;
    positions.yu=yu;
    positions.zu=zu;
    positions.xv=xv;
    positions.yv=yv;
    positions.zv=zv;
    positions.xs1=xs1;
    positions.ys1=ys1;
    positions.zs1=zs1;
    positions.xu1=xu1;
    positions.yu1=yu1;
    positions.zu1=zu1;
    positions.xv1=xv1;
    positions.yv1=yv1;
    positions.zv1=zv1;
    positions.x_target=x_target;
    positions.y_target=y_target;
    positions.z_target=z_target;
    disp(positions);
    fileID=fopen('claw_machine.txt','a');
    dispcontent=positions;
    fprintf(fileID,'[%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f]\n',positions.xo,positions.yo,positions.zo,positions.xa,positions.ya,positions.za,positions.xb,positions.yb,positions.zb,positions.xc,positions.yc,positions.zc,positions.xd,positions.yd,positions.zd,positions.xe,positions.ye,positions.ze,positions.xf,positions.yf,positions.zf,positions.xg,positions.yg,positions.zg,positions.xh,positions.yh,positions.zh,positions.xi,positions.yi,positions.zi,positions.xj,positions.yj,positions.zj,positions.xk,positions.yk,positions.zk,positions.xl,positions.yl,positions.zl,positions.xm,positions.ym,positions.zm,positions.xp,positions.yp,positions.zp,positions.xq,positions.yq,positions.zq,positions.xs,positions.ys,positions.zs,positions.xu,positions.yu,positions.zu,positions.xv,positions.yv,positions.zv,positions.xs1,positions.ys1,positions.zs1,positions.xu1,positions.yu1,positions.zu1,positions.xv1,positions.yv1,positions.zv1,positions.x_target,positions.y_target,positions.z_target,x_ball1,y_ball1,z_ball1,x_ball2,y_ball2,z_ball2,x_ball3,y_ball3,z_ball3,x_ball4,y_ball4,z_ball4);



end;

L_tri=4;

for i=27:-0.5:21
    xo=0;
    yo=5;
    zo=i;
    x_target=xo;
    y_target=yo;
    z_target=zo;
    xa=xo+L_tri/2;
    ya=yo-L_tri/(2*3^0.5);
    za=zo;
    xb=xo-L_tri/2;
    yb=yo-L_tri/(2*3^0.5);
    zb=zo;
    xc=xo;
    yc=yo+L_tri/(3^0.5);
    zc=zo;
    xg=10*cos(pi/6);
    yg=-10*sin(pi/6);
    zg=0;
    xh=-xg;
    yh=yg;
    zh=zg;
    xi=0;
    yi=10;
    zi=0;

    L1=20.8;
    L2=10.8;
    syms xd yd zd xe ye ze xf yf zf;
    eq1=(xd-xa)^2+(yd-ya)^2+(za-zd)^2==L1^2;
    eq2=(xd-xg)^2+(yd-yg)^2+(zd-zg)^2==L2^2;
    eq3=xd==xg;

    eq4=(xb-xe)^2+(yb-ye)^2+(zb-ze)^2==L1^2;
    eq5=(xh-xe)^2+(yh-ye)^2+(zh-ze)^2==L2^2;
    eq6=xe-xh==(yh-ye)*3^0.5;

    eq7=(xc-xf)^2+(yc-yf)^2+(zc-zf)^2==L1^2;
    eq8=(xi-xf)^2+(yi-yf)^2+(zi-zf)^2==L2^2;
    eq9=xi-xf==(yi-yf)*3^0.5;

    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xd,yd,zd,xe,ye,ze,xf,yf,zf]);
    xd=double(sol.xd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yd=double(sol.yd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zd=double(sol.zd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xe=double(sol.xe(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ye=double(sol.ye(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ze=double(sol.ze(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xf=double(sol.xf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yf=double(sol.yf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zf=double(sol.zf(sol.yd>0 & sol.xe>-5 & sol.xf<0));

    L3=4.4;
    L4=4.2;
    L5=5.3;
    xj=xg;
    yj=yg+L3*(zd-zg)/L2;
    zj=zg-L3*(yd-yg)/L2;

    syms xk yk zk;
    eq1=(xk-xh)^2+(yk-yh)^2+(zk-zh)^2==L3^2;
    eq2=(xk-xe)^2+(yk-ye)^2+(zk-ze)^2==L3^2+L2^2;
    eq3=-sin(pi/6)*(xk-xh)-cos(pi/6)*(yk-yh)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xk,yk,zk]);
    xk=double(sol.xk(sol.xk>xh));
    yk=double(sol.yk(sol.xk>xh));
    zk=double(sol.zk(sol.xk>xh));

    syms xl yl zl;
    eq1=(xl-xi)^2+(yl-yi)^2+(zl-zi)^2==L3^2;
    eq2=(xl-xf)^2+(yl-yf)^2+(zl-zf)^2==L2^2+L3^2;
    eq3=-sin(pi/6)*(xl-xi)+cos(pi/6)*(yl-yi)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xl,yl,zl]);
    xl=double(sol.xl(sol.xl<0));
    yl=double(sol.yl(sol.xl<0));
    zl=double(sol.zl(sol.xl<0));

    xs=6*sin(pi/6);
    ys=-6*cos(pi/6);
    zs=-1;
    xu=-6;
    yu=0;
    zu=-1;
    xv=xs;
    yv=-ys;
    zv=-1;

    syms xm ym zm xp yp zp xq yq zq;
    eq1=(xm-xj)^2+(ym-yj)^2+(zm-zj)^2==L4^2;
    eq2=(xm-xs)^2+(ym-ys)^2+(zm-zs)^2==L5^2;
    eq3=zs==zm;
    eq4=(xp-xk)^2+(yp-yk)^2+(zp-zk)^2==L4^2;
    eq5=(xp-xu)^2+(yp-yu)^2+(zp-zu)^2==L5^2;
    eq6=zp==zu;
    eq7=(xq-xl)^2+(yq-yl)^2+(zq-zl)^2==L4^2;
    eq8=(xq-xv)^2+(yq-yv)^2+(zq-zv)^2==L5^2;
    eq9=zq==zv;
    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xm,ym,zm,xp,yp,zp,xq,yq,zq]);
    xm=double(sol.xm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    ym=double(sol.ym(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zm=double(sol.zm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xp=double(sol.xp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yp=double(sol.yp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zp=double(sol.zp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xq=double(sol.xq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yq=double(sol.yq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zq=double(sol.zq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));


    alpha=pi*3/4;
    L6=2.5;
    xs1=xs+L6*cos(alpha+atan2(ym-ys,xm-xs));
    ys1=ys+L6*sin(alpha+atan2(ym-ys,xm-xs));
    zs1=zm;
    xu1=xu+L6*cos(alpha+atan2(yp-yu,xp-xu));
    yu1=yu+L6*sin(alpha+atan2(yp-yu,xp-xu));
    zu1=zp;
    xv1=xv+L6*cos(alpha+atan2(yq-yv,xq-xv));
    yv1=yv+L6*sin(alpha+atan2(yq-yv,xq-xv));
    zv1=zq;

    rho_s=(xs1^2+ys1^2+zs1^2)^0.5;
    rho_u=(xu1^2+yu1^2+zu1^2)^0.5;
    rho_v=(xv1^2+yv1^2+zv1^2)^0.5;

    positions.xo=xo;
    positions.yo=yo;
    positions.zo=zo;
    positions.xa=xa;
    positions.ya=ya;
    positions.za=za;
    positions.xb=xb;
    positions.yb=yb;
    positions.zb=zb;
    positions.xc=xc;
    positions.yc=yc;
    positions.zc=zc;
    positions.xd=xd;
    positions.yd=yd;
    positions.zd=zd;
    positions.xe=xe;
    positions.ye=ye;
    positions.ze=ze;
    positions.xf=xf;
    positions.yf=yf;
    positions.zf=zf;
    positions.xg=xg;
    positions.yg=yg;
    positions.zg=zg;
    positions.xh=xh;
    positions.yh=yh;
    positions.zh=zh;
    positions.xi=xi;
    positions.yi=yi;
    positions.zi=zi;
    positions.xj=xj;
    positions.yj=yj;
    positions.zj=zj;
    positions.xk=xk;
    positions.yk=yk;
    positions.zk=zk;
    positions.xl=xl;
    positions.yl=yl;
    positions.zl=zl;
    positions.xm=xm;
    positions.ym=ym;
    positions.zm=zm;
    positions.xp=xp;
    positions.yp=yp;
    positions.zp=zp;
    positions.xq=xq;
    positions.yq=yq;
    positions.zq=zq;
    positions.xs=xs;
    positions.ys=ys;
    positions.zs=zs;
    positions.xu=xu;
    positions.yu=yu;
    positions.zu=zu;
    positions.xv=xv;
    positions.yv=yv;
    positions.zv=zv;
    positions.xs1=xs1;
    positions.ys1=ys1;
    positions.zs1=zs1;
    positions.xu1=xu1;
    positions.yu1=yu1;
    positions.zu1=zu1;
    positions.xv1=xv1;
    positions.yv1=yv1;
    positions.zv1=zv1;
    positions.x_target=x_target;
    positions.y_target=y_target;
    positions.z_target=z_target;
    disp(positions);
    fileID=fopen('claw_machine.txt','a');
    dispcontent=positions;
    fprintf(fileID,'[%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f]\n',positions.xo,positions.yo,positions.zo,positions.xa,positions.ya,positions.za,positions.xb,positions.yb,positions.zb,positions.xc,positions.yc,positions.zc,positions.xd,positions.yd,positions.zd,positions.xe,positions.ye,positions.ze,positions.xf,positions.yf,positions.zf,positions.xg,positions.yg,positions.zg,positions.xh,positions.yh,positions.zh,positions.xi,positions.yi,positions.zi,positions.xj,positions.yj,positions.zj,positions.xk,positions.yk,positions.zk,positions.xl,positions.yl,positions.zl,positions.xm,positions.ym,positions.zm,positions.xp,positions.yp,positions.zp,positions.xq,positions.yq,positions.zq,positions.xs,positions.ys,positions.zs,positions.xu,positions.yu,positions.zu,positions.xv,positions.yv,positions.zv,positions.xs1,positions.ys1,positions.zs1,positions.xu1,positions.yu1,positions.zu1,positions.xv1,positions.yv1,positions.zv1,positions.x_target,positions.y_target,positions.z_target,x_ball1,y_ball1,z_ball1,x_ball2,y_ball2,z_ball2,x_ball3,y_ball3,z_ball3,x_ball4,y_ball4,z_ball4);


end;

for i=1/12:1/12:11/12
    
    xo=i*5*cos(pi/6);
    yo=5+i*(5*sin(pi/6)-5);
    zo=21;
    x_target=xo;
    y_target=yo;
    z_target=zo;
    xa=xo+L_tri/2;
    ya=yo-L_tri/(2*3^0.5);
    za=zo;
    xb=xo-L_tri/2;
    yb=yo-L_tri/(2*3^0.5);
    zb=zo;
    xc=xo;
    yc=yo+L_tri/(3^0.5);
    zc=zo;
    xg=10*cos(pi/6);
    yg=-10*sin(pi/6);
    zg=0;
    xh=-xg;
    yh=yg;
    zh=zg;
    xi=0;
    yi=10;
    zi=0;

    L1=20.8;
    L2=10.8;
    syms xd yd zd xe ye ze xf yf zf;
    eq1=(xd-xa)^2+(yd-ya)^2+(za-zd)^2==L1^2;
    eq2=(xd-xg)^2+(yd-yg)^2+(zd-zg)^2==L2^2;
    eq3=xd==xg;

    eq4=(xb-xe)^2+(yb-ye)^2+(zb-ze)^2==L1^2;
    eq5=(xh-xe)^2+(yh-ye)^2+(zh-ze)^2==L2^2;
    eq6=xe-xh==(yh-ye)*3^0.5;

    eq7=(xc-xf)^2+(yc-yf)^2+(zc-zf)^2==L1^2;
    eq8=(xi-xf)^2+(yi-yf)^2+(zi-zf)^2==L2^2;
    eq9=xi-xf==(yi-yf)*3^0.5;

    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xd,yd,zd,xe,ye,ze,xf,yf,zf]);
    xd=double(sol.xd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yd=double(sol.yd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zd=double(sol.zd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xe=double(sol.xe(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ye=double(sol.ye(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ze=double(sol.ze(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xf=double(sol.xf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yf=double(sol.yf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zf=double(sol.zf(sol.yd>0 & sol.xe>-5 & sol.xf<0));

    L3=4.4;
    L4=4.2;
    L5=5.3;
    xj=xg;
    yj=yg+L3*(zd-zg)/L2;
    zj=zg-L3*(yd-yg)/L2;

    syms xk yk zk;
    eq1=(xk-xh)^2+(yk-yh)^2+(zk-zh)^2==L3^2;
    eq2=(xk-xe)^2+(yk-ye)^2+(zk-ze)^2==L3^2+L2^2;
    eq3=-sin(pi/6)*(xk-xh)-cos(pi/6)*(yk-yh)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xk,yk,zk]);
    xk=double(sol.xk(sol.xk>xh));
    yk=double(sol.yk(sol.xk>xh));
    zk=double(sol.zk(sol.xk>xh));

    syms xl yl zl;
    eq1=(xl-xi)^2+(yl-yi)^2+(zl-zi)^2==L3^2;
    eq2=(xl-xf)^2+(yl-yf)^2+(zl-zf)^2==L2^2+L3^2;
    eq3=-sin(pi/6)*(xl-xi)+cos(pi/6)*(yl-yi)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xl,yl,zl]);
    xl=double(sol.xl(sol.xl<0));
    yl=double(sol.yl(sol.xl<0));
    zl=double(sol.zl(sol.xl<0));

    xs=6*sin(pi/6);
    ys=-6*cos(pi/6);
    zs=-1;
    xu=-6;
    yu=0;
    zu=-1;
    xv=xs;
    yv=-ys;
    zv=-1;

    syms xm ym zm xp yp zp xq yq zq;
    eq1=(xm-xj)^2+(ym-yj)^2+(zm-zj)^2==L4^2;
    eq2=(xm-xs)^2+(ym-ys)^2+(zm-zs)^2==L5^2;
    eq3=zs==zm;
    eq4=(xp-xk)^2+(yp-yk)^2+(zp-zk)^2==L4^2;
    eq5=(xp-xu)^2+(yp-yu)^2+(zp-zu)^2==L5^2;
    eq6=zp==zu;
    eq7=(xq-xl)^2+(yq-yl)^2+(zq-zl)^2==L4^2;
    eq8=(xq-xv)^2+(yq-yv)^2+(zq-zv)^2==L5^2;
    eq9=zq==zv;
    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xm,ym,zm,xp,yp,zp,xq,yq,zq]);
    xm=double(sol.xm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    ym=double(sol.ym(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zm=double(sol.zm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xp=double(sol.xp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yp=double(sol.yp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zp=double(sol.zp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xq=double(sol.xq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yq=double(sol.yq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zq=double(sol.zq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));


    alpha=pi*3/4;
    L6=2.5;
    xs1=xs+L6*cos(alpha+atan2(ym-ys,xm-xs));
    ys1=ys+L6*sin(alpha+atan2(ym-ys,xm-xs));
    zs1=zm;
    xu1=xu+L6*cos(alpha+atan2(yp-yu,xp-xu));
    yu1=yu+L6*sin(alpha+atan2(yp-yu,xp-xu));
    zu1=zp;
    xv1=xv+L6*cos(alpha+atan2(yq-yv,xq-xv));
    yv1=yv+L6*sin(alpha+atan2(yq-yv,xq-xv));
    zv1=zq;

    rho_s=(xs1^2+ys1^2+zs1^2)^0.5;
    rho_u=(xu1^2+yu1^2+zu1^2)^0.5;
    rho_v=(xv1^2+yv1^2+zv1^2)^0.5;

    positions.xo=xo;
    positions.yo=yo;
    positions.zo=zo;
    positions.xa=xa;
    positions.ya=ya;
    positions.za=za;
    positions.xb=xb;
    positions.yb=yb;
    positions.zb=zb;
    positions.xc=xc;
    positions.yc=yc;
    positions.zc=zc;
    positions.xd=xd;
    positions.yd=yd;
    positions.zd=zd;
    positions.xe=xe;
    positions.ye=ye;
    positions.ze=ze;
    positions.xf=xf;
    positions.yf=yf;
    positions.zf=zf;
    positions.xg=xg;
    positions.yg=yg;
    positions.zg=zg;
    positions.xh=xh;
    positions.yh=yh;
    positions.zh=zh;
    positions.xi=xi;
    positions.yi=yi;
    positions.zi=zi;
    positions.xj=xj;
    positions.yj=yj;
    positions.zj=zj;
    positions.xk=xk;
    positions.yk=yk;
    positions.zk=zk;
    positions.xl=xl;
    positions.yl=yl;
    positions.zl=zl;
    positions.xm=xm;
    positions.ym=ym;
    positions.zm=zm;
    positions.xp=xp;
    positions.yp=yp;
    positions.zp=zp;
    positions.xq=xq;
    positions.yq=yq;
    positions.zq=zq;
    positions.xs=xs;
    positions.ys=ys;
    positions.zs=zs;
    positions.xu=xu;
    positions.yu=yu;
    positions.zu=zu;
    positions.xv=xv;
    positions.yv=yv;
    positions.zv=zv;
    positions.xs1=xs1;
    positions.ys1=ys1;
    positions.zs1=zs1;
    positions.xu1=xu1;
    positions.yu1=yu1;
    positions.zu1=zu1;
    positions.xv1=xv1;
    positions.yv1=yv1;
    positions.zv1=zv1;
    positions.x_target=x_target;
    positions.y_target=y_target;
    positions.z_target=z_target;
    disp(positions);
    fileID=fopen('claw_machine.txt','a');
    dispcontent=positions;
    fprintf(fileID,'[%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f]\n',positions.xo,positions.yo,positions.zo,positions.xa,positions.ya,positions.za,positions.xb,positions.yb,positions.zb,positions.xc,positions.yc,positions.zc,positions.xd,positions.yd,positions.zd,positions.xe,positions.ye,positions.ze,positions.xf,positions.yf,positions.zf,positions.xg,positions.yg,positions.zg,positions.xh,positions.yh,positions.zh,positions.xi,positions.yi,positions.zi,positions.xj,positions.yj,positions.zj,positions.xk,positions.yk,positions.zk,positions.xl,positions.yl,positions.zl,positions.xm,positions.ym,positions.zm,positions.xp,positions.yp,positions.zp,positions.xq,positions.yq,positions.zq,positions.xs,positions.ys,positions.zs,positions.xu,positions.yu,positions.zu,positions.xv,positions.yv,positions.zv,positions.xs1,positions.ys1,positions.zs1,positions.xu1,positions.yu1,positions.zu1,positions.xv1,positions.yv1,positions.zv1,positions.x_target,positions.y_target,positions.z_target,x_ball1,y_ball1,z_ball1,x_ball2,y_ball2,z_ball2,x_ball3,y_ball3,z_ball3,x_ball4,y_ball4,z_ball4);



end;

L_tri=7.5;

for i=3.5:-0.5:0
    xo=5*cos(pi/6);
    yo=5*sin(pi/6);
    zo=21;
    L=L_tri-i;
    z_target=zo+(3.5-i)^2

    xa=xo+L/2;
    ya=yo-L/(2*3^0.5);
    za=zo;
    xb=xo-L/2;
    yb=yo-L/(2*3^0.5);
    zb=zo;
    xc=xo;
    yc=yo+L/(3^0.5);
    zc=zo;
    xg=10*cos(pi/6);
    yg=-10*sin(pi/6);
    zg=0;
    xh=-xg;
    yh=yg;
    zh=zg;
    xi=0;
    yi=10;
    zi=0;

    L1=20.8;
    L2=10.8;
    syms xd yd zd xe ye ze xf yf zf;
    eq1=(xd-xa)^2+(yd-ya)^2+(za-zd)^2==L1^2;
    eq2=(xd-xg)^2+(yd-yg)^2+(zd-zg)^2==L2^2;
    eq3=xd==xg;

    eq4=(xb-xe)^2+(yb-ye)^2+(zb-ze)^2==L1^2;
    eq5=(xh-xe)^2+(yh-ye)^2+(zh-ze)^2==L2^2;
    eq6=xe-xh==(yh-ye)*3^0.5;

    eq7=(xc-xf)^2+(yc-yf)^2+(zc-zf)^2==L1^2;
    eq8=(xi-xf)^2+(yi-yf)^2+(zi-zf)^2==L2^2;
    eq9=xi-xf==(yi-yf)*3^0.5;

    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xd,yd,zd,xe,ye,ze,xf,yf,zf]);
    xd=double(sol.xd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yd=double(sol.yd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zd=double(sol.zd(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xe=double(sol.xe(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ye=double(sol.ye(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    ze=double(sol.ze(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    xf=double(sol.xf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    yf=double(sol.yf(sol.yd>0 & sol.xe>-5 & sol.xf<0));
    zf=double(sol.zf(sol.yd>0 & sol.xe>-5 & sol.xf<0));

    L3=4.4;
    L4=4.2;
    L5=5.3;
    xj=xg;
    yj=yg+L3*(zd-zg)/L2;
    zj=zg-L3*(yd-yg)/L2;

    syms xk yk zk;
    eq1=(xk-xh)^2+(yk-yh)^2+(zk-zh)^2==L3^2;
    eq2=(xk-xe)^2+(yk-ye)^2+(zk-ze)^2==L3^2+L2^2;
    eq3=-sin(pi/6)*(xk-xh)-cos(pi/6)*(yk-yh)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xk,yk,zk]);
    xk=double(sol.xk(sol.xk>xh));
    yk=double(sol.yk(sol.xk>xh));
    zk=double(sol.zk(sol.xk>xh));

    syms xl yl zl;
    eq1=(xl-xi)^2+(yl-yi)^2+(zl-zi)^2==L3^2;
    eq2=(xl-xf)^2+(yl-yf)^2+(zl-zf)^2==L2^2+L3^2;
    eq3=-sin(pi/6)*(xl-xi)+cos(pi/6)*(yl-yi)==0;
    eqns=[eq1,eq2,eq3];
    sol=solve(eqns,[xl,yl,zl]);
    xl=double(sol.xl(sol.xl<0));
    yl=double(sol.yl(sol.xl<0));
    zl=double(sol.zl(sol.xl<0));

    xs=6*sin(pi/6);
    ys=-6*cos(pi/6);
    zs=-1;
    xu=-6;
    yu=0;
    zu=-1;
    xv=xs;
    yv=-ys;
    zv=-1;

    syms xm ym zm xp yp zp xq yq zq;
    eq1=(xm-xj)^2+(ym-yj)^2+(zm-zj)^2==L4^2;
    eq2=(xm-xs)^2+(ym-ys)^2+(zm-zs)^2==L5^2;
    eq3=zs==zm;
    eq4=(xp-xk)^2+(yp-yk)^2+(zp-zk)^2==L4^2;
    eq5=(xp-xu)^2+(yp-yu)^2+(zp-zu)^2==L5^2;
    eq6=zp==zu;
    eq7=(xq-xl)^2+(yq-yl)^2+(zq-zl)^2==L4^2;
    eq8=(xq-xv)^2+(yq-yv)^2+(zq-zv)^2==L5^2;
    eq9=zq==zv;
    eqns=[eq1,eq2,eq3,eq4,eq5,eq6,eq7,eq8,eq9];
    sol=solve(eqns,[xm,ym,zm,xp,yp,zp,xq,yq,zq]);
    xm=double(sol.xm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    ym=double(sol.ym(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zm=double(sol.zm(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xp=double(sol.xp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yp=double(sol.yp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zp=double(sol.zp(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    xq=double(sol.xq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    yq=double(sol.yq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));
    zq=double(sol.zq(sol.ym>-3 & sol.xp>-6.3 & sol.yq<8.2));


    alpha=pi*3/4;
    L6=2.5;
    xs1=xs+L6*cos(alpha+atan2(ym-ys,xm-xs));
    ys1=ys+L6*sin(alpha+atan2(ym-ys,xm-xs));
    zs1=zm;
    xu1=xu+L6*cos(alpha+atan2(yp-yu,xp-xu));
    yu1=yu+L6*sin(alpha+atan2(yp-yu,xp-xu));
    zu1=zp;
    xv1=xv+L6*cos(alpha+atan2(yq-yv,xq-xv));
    yv1=yv+L6*sin(alpha+atan2(yq-yv,xq-xv));
    zv1=zq;

    rho_s=(xs1^2+ys1^2+zs1^2)^0.5;
    rho_u=(xu1^2+yu1^2+zu1^2)^0.5;
    rho_v=(xv1^2+yv1^2+zv1^2)^0.5;

    positions.xo=xo;
    positions.yo=yo;
    positions.zo=zo;
    positions.xa=xa;
    positions.ya=ya;
    positions.za=za;
    positions.xb=xb;
    positions.yb=yb;
    positions.zb=zb;
    positions.xc=xc;
    positions.yc=yc;
    positions.zc=zc;
    positions.xd=xd;
    positions.yd=yd;
    positions.zd=zd;
    positions.xe=xe;
    positions.ye=ye;
    positions.ze=ze;
    positions.xf=xf;
    positions.yf=yf;
    positions.zf=zf;
    positions.xg=xg;
    positions.yg=yg;
    positions.zg=zg;
    positions.xh=xh;
    positions.yh=yh;
    positions.zh=zh;
    positions.xi=xi;
    positions.yi=yi;
    positions.zi=zi;
    positions.xj=xj;
    positions.yj=yj;
    positions.zj=zj;
    positions.xk=xk;
    positions.yk=yk;
    positions.zk=zk;
    positions.xl=xl;
    positions.yl=yl;
    positions.zl=zl;
    positions.xm=xm;
    positions.ym=ym;
    positions.zm=zm;
    positions.xp=xp;
    positions.yp=yp;
    positions.zp=zp;
    positions.xq=xq;
    positions.yq=yq;
    positions.zq=zq;
    positions.xs=xs;
    positions.ys=ys;
    positions.zs=zs;
    positions.xu=xu;
    positions.yu=yu;
    positions.zu=zu;
    positions.xv=xv;
    positions.yv=yv;
    positions.zv=zv;
    positions.xs1=xs1;
    positions.ys1=ys1;
    positions.zs1=zs1;
    positions.xu1=xu1;
    positions.yu1=yu1;
    positions.zu1=zu1;
    positions.xv1=xv1;
    positions.yv1=yv1;
    positions.zv1=zv1;
    positions.x_target=x_target;
    positions.y_target=y_target;
    positions.z_target=z_target;
    disp(positions);
    fileID=fopen('claw_machine.txt','a');
    dispcontent=positions;
    fprintf(fileID,'[%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f]\n',positions.xo,positions.yo,positions.zo,positions.xa,positions.ya,positions.za,positions.xb,positions.yb,positions.zb,positions.xc,positions.yc,positions.zc,positions.xd,positions.yd,positions.zd,positions.xe,positions.ye,positions.ze,positions.xf,positions.yf,positions.zf,positions.xg,positions.yg,positions.zg,positions.xh,positions.yh,positions.zh,positions.xi,positions.yi,positions.zi,positions.xj,positions.yj,positions.zj,positions.xk,positions.yk,positions.zk,positions.xl,positions.yl,positions.zl,positions.xm,positions.ym,positions.zm,positions.xp,positions.yp,positions.zp,positions.xq,positions.yq,positions.zq,positions.xs,positions.ys,positions.zs,positions.xu,positions.yu,positions.zu,positions.xv,positions.yv,positions.zv,positions.xs1,positions.ys1,positions.zs1,positions.xu1,positions.yu1,positions.zu1,positions.xv1,positions.yv1,positions.zv1,positions.x_target,positions.y_target,positions.z_target,x_ball1,y_ball1,z_ball1,x_ball2,y_ball2,z_ball2,x_ball3,y_ball3,z_ball3,x_ball4,y_ball4,z_ball4);

end;

fclose(fileID);